source 'https://github.com/CocoaPods/Specs.git'
source 'ssh://git@git.1kxun.com:9922/ios/CocoaPods-Specs.git'

use_frameworks!

target 'TCNDeviceInfo_Example' do
  pod 'TCNDeviceInfo', :path => '../'

  target 'TCNDeviceInfo_Tests' do
    inherit! :search_paths

    
  end
end
